# Generated by Django 4.2.1 on 2026-09-01 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OpenBench', '0011_normalize_engine_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='updated',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
