# Generated by Django 4.2.1 on 2026-09-04 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("OpenBench", "0012_alter_machine_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="result",
            name="base_nodes",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="result",
            name="base_time",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="result",
            name="base_time_scaled",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="result",
            name="dev_nodes",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="result",
            name="dev_time",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="result",
            name="dev_time_scaled",
            field=models.BigIntegerField(default=0),
        ),
    ]
